language: cpp
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      - boost-latest/ppa
      - kubuntu-backports # cmake 2.8.12
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - g++-multilib
      - python-nose
      - python3-nose
      - python3.5
      - python3.5-dev
      - python3.5-venv
      - libhdf5-serial-dev
      - libboost-all-dev
      - libglpk-dev
      - cmake
      #- libboost-test-dev 
      ## 
#before_script:
#  - wget https://github.com/wjakob/pybind11/archive/master.zip
#  - unzip master.zip -d .
#  #
matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      script:
        - pyvenv-3.5 venv
        - cmake -DWITHIN_TRAVIS=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DCMAKE_CXX_COMPILER=g++-4.8 -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        #- cmake -DWITHIN_TRAVIS=ON -DWITH_GLPK=ON -DWITH_HDF5=ON -DBUILD_NIFTY_PYTHON=ON -DPYBIND_ELEVEN_INCLUDE_DIR=pybind11-master/include -DCMAKE_CXX_COMPILER=g++-4.8 -DPYBIND11_PYTHON_VERSION=3.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.5m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.5m.so -DPYTHON_EXECUTABLE:FILEPATH=`pwd`/venv/bin/python3.5 
        - make -j2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        #- make python-test
        #- source venv/bin/activate
        #- pip install numpy
        #- CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - os: osx
      compiler: clang
      script:
        - cmake -DWITHIN_TRAVIS=ON -DWITH_GLPK=OFF -DBUILD_NIFTY_PYTHON=ON -DPYBIND_ELEVEN_INCLUDE_DIR=pybind11-master/include -DPYBIND11_PYTHON_VERSION=2.7
        - make -j 2
        - CTEST_OUTPUT_ON_FAILURE=TRUE make test
        #- make python-test