name: nifty-build-env
channels:
  - conda-forge
dependencies:
  - boost-cpp>=1.63
  - cmake
  - compilers
  - h5py
  - nlohmann_json
  - scikit-image
  - xtensor
  - xtensor-python
  - vigra
  - z5py
